"""add tables Like and LikeComment with unique constraints

Revision ID: 894e896bd4a5
Revises: bad1d0c87808
Create Date: 2026-02-26 12:02:19.838712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '894e896bd4a5'
down_revision: Union[str, Sequence[str], None] = 'bad1d0c87808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_author_comment', 'likecomments', ['author_id', 'comment_id'])
    op.create_unique_constraint('uix_author_post', 'likes', ['author_id', 'post_id'])
    op.create_unique_constraint(None, 'likes', ['post_id'])
    op.create_unique_constraint(None, 'likes', ['author_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='unique')
    op.drop_constraint(None, 'likes', type_='unique')
    op.drop_constraint('uix_author_post', 'likes', type_='unique')
    op.drop_constraint('uix_author_comment', 'likecomments', type_='unique')
    # ### end Alembic commands ###
