"""add table: attachment, change table: post

Revision ID: a651e6613580
Revises: fd71a63943c7
Create Date: 2026-02-23 10:54:09.550181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a651e6613580'
down_revision: Union[str, Sequence[str], None] = 'fd71a63943c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content', sa.String(), nullable=True))
    op.drop_column('posts', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('type', postgresql.ENUM('TEXT', 'IMAGE', 'VIDEO', name='post_type_enum'), autoincrement=False, nullable=False))
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###
