"""add table: like comment

Revision ID: bad1d0c87808
Revises: a651e6613580
Create Date: 2026-02-26 11:49:06.138627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad1d0c87808'
down_revision: Union[str, Sequence[str], None] = 'a651e6613580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('author_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('likes_user_id_fkey'), 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'users', ['author_id'], ['id'])
    op.drop_column('likes', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key(op.f('likes_user_id_fkey'), 'likes', 'users', ['user_id'], ['id'])
    op.drop_column('likes', 'author_id')
    # ### end Alembic commands ###
