"""Modified the Post model and added the PostMedia model

Revision ID: e283d67fca3d
Revises: 9fe5624cacc9
Create Date: 2026-08-11 11:13:44.704753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e283d67fca3d'
down_revision: Union[str, Sequence[str], None] = '9fe5624cacc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_medias',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', name='mediatype'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_posts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('post_type', sa.Enum('POST', 'REEL', name='posttype'), nullable=False))
    op.add_column('posts', sa.Column('caption', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('visibility', sa.Enum('PUBLIC', 'FOLLOWERS', 'PRIVATE', name='postvisibility'), nullable=False))
    op.add_column('posts', sa.Column('comments_enabled', sa.Boolean(), nullable=False))
    op.drop_column('posts', 'content')
    op.drop_constraint(op.f('user_follows_follower_id_key'), 'user_follows', type_='unique')
    op.drop_constraint(op.f('user_follows_following_id_key'), 'user_follows', type_='unique')
    op.create_index('ix_user_follows_follower_created_at', 'user_follows', ['follower_id', 'created_at'], unique=False)
    op.create_index('ix_user_follows_following_created_at', 'user_follows', ['following_id', 'created_at'], unique=False)
    op.create_unique_constraint('uq_user_follows_follower_following', 'user_follows', ['follower_id', 'following_id'])
    op.create_check_constraint('ck_user_follows_no_self_follow', 'user_follows', 'follower_id != following_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_user_follows_no_self_follow', 'user_follows', type_='check')
    op.drop_constraint('uq_user_follows_follower_following', 'user_follows', type_='unique')
    op.drop_index('ix_user_follows_following_created_at', table_name='user_follows')
    op.drop_index('ix_user_follows_follower_created_at', table_name='user_follows')
    op.create_unique_constraint(op.f('user_follows_following_id_key'), 'user_follows', ['following_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('user_follows_follower_id_key'), 'user_follows', ['follower_id'], postgresql_nulls_not_distinct=False)
    op.add_column('posts', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'comments_enabled')
    op.drop_column('posts', 'visibility')
    op.drop_column('posts', 'location')
    op.drop_column('posts', 'caption')
    op.drop_column('posts', 'post_type')
    op.drop_table('saved_posts')
    op.drop_table('post_medias')
    # ### end Alembic commands ###
