"""Change models Favorite, Like, ChatParticipant and delete model Attachment

Revision ID: edc03530af61
Revises: 5f06a5e1fb2f
Create Date: 2026-08-14 08:47:31.584993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edc03530af61'
down_revision: Union[str, Sequence[str], None] = '5f06a5e1fb2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    op.create_index(op.f('ix_chat_participants_chat_id'), 'chat_participants', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_participants_user_id'), 'chat_participants', ['user_id'], unique=False)
    op.create_unique_constraint('uq_chat_participants_chat_user', 'chat_participants', ['chat_id', 'user_id'])
    op.drop_constraint(op.f('chat_participants_chat_id_fkey'), 'chat_participants', type_='foreignkey')
    op.drop_constraint(op.f('chat_participants_chat_role_id_fkey'), 'chat_participants', type_='foreignkey')
    op.drop_constraint(op.f('chat_participants_user_id_fkey'), 'chat_participants', type_='foreignkey')
    op.create_foreign_key(None, 'chat_participants', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_participants', 'chat_roles', ['chat_role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_participants', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_favorites_post_id'), 'favorites', ['post_id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_unique_constraint('uq_favorites_user_post', 'favorites', ['user_id', 'post_id'])
    op.drop_constraint(op.f('favorites_post_id_fkey'), 'favorites', type_='foreignkey')
    op.drop_constraint(op.f('favorites_user_id_fkey'), 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'favorites', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('likes_author_id_key'), 'likes', type_='unique')
    op.drop_constraint(op.f('likes_post_id_key'), 'likes', type_='unique')
    op.drop_constraint(op.f('uix_author_post'), 'likes', type_='unique')
    op.create_index(op.f('ix_likes_author_id'), 'likes', ['author_id'], unique=False)
    op.create_index(op.f('ix_likes_post_id'), 'likes', ['post_id'], unique=False)
    op.create_unique_constraint('uq_likes_author_post', 'likes', ['author_id', 'post_id'])
    op.drop_constraint(op.f('likes_author_id_fkey'), 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key(op.f('likes_author_id_fkey'), 'likes', 'users', ['author_id'], ['id'])
    op.drop_constraint('uq_likes_author_post', 'likes', type_='unique')
    op.drop_index(op.f('ix_likes_post_id'), table_name='likes')
    op.drop_index(op.f('ix_likes_author_id'), table_name='likes')
    op.create_unique_constraint(op.f('uix_author_post'), 'likes', ['author_id', 'post_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('likes_post_id_key'), 'likes', ['post_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('likes_author_id_key'), 'likes', ['author_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key(op.f('favorites_user_id_fkey'), 'favorites', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('favorites_post_id_fkey'), 'favorites', 'posts', ['post_id'], ['id'])
    op.drop_constraint('uq_favorites_user_post', 'favorites', type_='unique')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_post_id'), table_name='favorites')
    op.drop_constraint(None, 'chat_participants', type_='foreignkey')
    op.drop_constraint(None, 'chat_participants', type_='foreignkey')
    op.drop_constraint(None, 'chat_participants', type_='foreignkey')
    op.create_foreign_key(op.f('chat_participants_user_id_fkey'), 'chat_participants', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('chat_participants_chat_role_id_fkey'), 'chat_participants', 'chat_roles', ['chat_role_id'], ['id'])
    op.create_foreign_key(op.f('chat_participants_chat_id_fkey'), 'chat_participants', 'chats', ['chat_id'], ['id'])
    op.drop_constraint('uq_chat_participants_chat_user', 'chat_participants', type_='unique')
    op.drop_index(op.f('ix_chat_participants_user_id'), table_name='chat_participants')
    op.drop_index(op.f('ix_chat_participants_chat_id'), table_name='chat_participants')
    op.create_table('attachments',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('attachments_post_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('attachments_pkey'))
    )
    # ### end Alembic commands ###
